version: '3'
services:
  node:
    user: '${USER_ID}:${GROUP_ID}'
    image: node:14-alpine
    command: yarn run dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3030:3030